require 'net/http'
require 'rexml/document'
require 'script/_testing/helpers/dbtools.rb'
require 'cgi'

$bookmaker = "PinnacleSports"

$sport_cache['PinnacleSports'] = {
  'Hockey' => 'Ice hockey',
  'Football' => 'American Football'
}

$iterations = 2
$last = nil

1.upto($iterations) {
  |i|
  url = "http://xml.pinnaclesports.com/pinnacleFeed.asp"
  url += "?last=#{$last}" if $last

  xml_data = Net::HTTP.get_response(URI.parse(url)).body

   File.open(['pinnacle', i].join('-')+'.xml', "w") { |f| f.write "<!-- GOTTEN FROM URL: '#{url}'\n     THIS COMMENT WAS GENERATED BY pinnacle.rb\n-->\n\n"; f.write xml_data; f.close }

  doc = REXML::Document.new(xml_data)

  interest = []

  moneylineevents = REXML::XPath.match(doc, 'pinnacle_line_feed/events/event[periods/period[period_number="0"]/moneyline]')

  moneylineevents.each do |event|
    $sport = event.elements['sporttype'].text
    league = event.elements['league'].text
    date = nil
    teams = REXML::XPath.first(event, 'participants')
    team1_name = REXML::XPath.first(teams, 'participant[visiting_home_draw="Home"]/participant_name').text
    team2_name = REXML::XPath.first(teams, 'participant[visiting_home_draw="Visiting"]/participant_name').text
    
    moneyline = REXML::XPath.first(event, 'periods/period[period_number="0"]/moneyline')
    q1 = REXML::XPath.first(moneyline, 'moneyline_home').text
    qx = REXML::XPath.first(moneyline, 'moneyline_draw')
    qx = qx.text unless qx.nil?
    q2 = REXML::XPath.first(moneyline, 'moneyline_visiting').text

    register_quote([league, date, team1_name, team2_name, q1, qx, q2])
  end

  $last = doc.elements['pinnacle_line_feed/PinnacleFeedTime'].text
}